variables:
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE: rwthacs/hugo-ext
  DOCKER_IMAGE_DEV: rwthacs/plf-docs

before_script:
  - git config --local core.longpaths true
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - prepare
  - build
  - deploy

docker:dev:
  stage: prepare
  script:
    - docker build
      --file Dockerfile_dev
      --tag ${DOCKER_IMAGE_DEV}:${DOCKER_TAG}
      --tag ${DOCKER_IMAGE_DEV}:latest .
#  artifacts:
#    paths:
#      - public
  tags:
    - shell
  only:
    - develop
  



docker:master:
  stage: prepare
  script:
    - docker build
      --file Dockerfile_master
      --tag ${DOCKER_IMAGE}:${DOCKER_TAG}
      --tag ${DOCKER_IMAGE}:latest .
#  artifacts:
#    paths:
#      - public
  tags:
    - shell
  only:
    - master
  

hugo:
  stage: build
  script:
    - npm install -D --save autoprefixer
    - npm install -D --save postcss-cli
    - npm audit fix --force
    - hugo -v
    - ls -l
  image: ${DOCKER_IMAGE}:${DOCKER_TAG}
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker


pages:
  stage: deploy
  script:
    - ls -l
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shell
    #- linux
    


