variables:
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE: rwthacs/hugo-ext

before_script:
  - git config --local core.longpaths true
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - prepare
  - build
  - deploy

docker:
 stage: prepare
 script:
   - docker build
       --tag ${DOCKER_IMAGE}:${DOCKER_TAG}
       --tag ${DOCKER_IMAGE}:latest .
 tags:
   - shell
  #  - linux
  # - docker

hugo:master:
  stage: build
  script:
    - npm install -D --save autoprefixer
    - npm install -D --save postcss-cli
    - npm audit fix --force
    - hugo -v
    - ls -l
  image: ${DOCKER_IMAGE}:${DOCKER_TAG}
  artifacts:
    name: "master"
    paths:
      - public
  tags:
    - docker
 
hugo:dev:
  stage: build
  script:
    - npm install -D --save autoprefixer
    - npm install -D --save postcss-cli
    - npm audit fix --force
    - hugo -v
    - ls -l
    - mv ./public ./public/dev
    - ls -l ./public
  image: ${DOCKER_IMAGE}:${DOCKER_TAG}
  artifacts:
    name: "dev"
    paths:
      - public
    expire_in: 1 week
  tags:
    - docker   


pages:
  stage: deploy
  script:
    - ls -l
  artifacts:
    name: "master"
    paths:
      - public
  only:
    - master
  tags:
    - shell
    #- linux
    
pages:
  stage: deploy
  script:
    - ls -l
  artifacts:
    name: "dev"
    paths:
      - public
    expire_in: 1 week
  only:
    - develop
  tags:
    - shell
    #- linux

